version: "3"
services:
  postgres:
    image: mdillon/postgis:10-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated

volumes:
  postgres-data:
